
domain_list=["globlow","globmid","globhig","globtop","npollow", "npolmid", "npolhig", "npoltop", "nortlow", "nortmid", "northig", "norttop", "troplow", "tropmid", "trophig", "troptop", "soutlow", "soutmid", "southig", "souttop", "spollow", "spolmid", "spolhig", "spoltop","indialow","indiamid","indiahig","indiatop"]

hgt_min={
	"low" : 0.0,
	"mid" : 3000.0,
	"hig" : 6000.0,
	"top" : 9000.0,
	}

hgt_max={
	"low" : 3000.0,
	"mid" : 6000.0,
	"hig" : 90000.0,
	"top" : 20000.0,
	}

lat_min={
	"glob" : -90.0,
	"npol" : 60.0,
	"nort" : 40.0,
	"trop" : -10.0,
	"sout" : -50.0,
	"spol" : -90.0,
	"indi" : 0.0,
	}

lat_max={
	"glob" : 90.0,
	"npol" : 90.0,
	"nort" : 50.0,
	"trop" : 10.0,
	"sout" : -40.0,
	"spol" : -60.0,
	"indi" : 35.0,
	}

lon_min={
	"glob" : -180.0,
	"indi" : 60.0,
	"psfc" : 180.0,
	}


lon_max={
	"glob" : 360.0,
	"indi" : 100.0,
	"psfc" : 300.0,
	}
	
	
dom_name={
	"globlow" : "Global low altitude",
	"globmid" : "Global middle altitude",
	"globhig" : "Global high altitude",
	"globtop" : "Global top layer",
	"npollow" : "North Polar low altitude",
	"npolmid" : "North Polar middle altitude",
	"npolhig" : "North Polar high altitude", 
	"npoltop" : "North Polar top layer",
	"nortlow" : "North Extratropical low altitude",
	"nortmid" : "North Extratropical middle altitude",
	"northig" : "North Extratropical high altitude",
	"norttop" : "North Extratropical top layer",
	"troplow" : "Tropical low altitude",
	"tropmid" : "Tropical middle altitude",
	"trophig" : "Tropical high altitude",
	"troptop" : "Tropical top layer",
	"soutlow" : "South Extratropical low altitude",
	"soutmid" : "South Extratropical middle altitude",
	"southig" : "South Extratropical high altitude",
	"souttop" : "South Extratropical top layer",
	"spollow" : "South Polar low altitude",
	"spolmid" : "South Polar middle altitude",
	"spolhig" : "South Polar high altitude", 
	"spoltop" : "South Polar top layer",
	"indialow" : "Global low altitude",
	"indiamid" : "Global middle altitude",
	"indiahig" : "Global high altitude",
	"indiatop" : "Global top layer",
	}

dom_lonmin={
	"globlow" : lon_min["glob"],
	"globmid" : lon_min["glob"],
	"globhig" : lon_min["glob"],
	"globtop" : lon_min["glob"],
	"npollow" : lon_min["glob"],
	"npolmid" : lon_min["glob"],
	"npolhig" : lon_min["glob"],
	"npoltop" : lon_min["glob"],
	"nortlow" : lon_min["glob"],
	"nortmid" : lon_min["glob"],
	"northig" : lon_min["glob"],
	"norttop" : lon_min["glob"],
	"troplow" : lon_min["glob"],
	"tropmid" : lon_min["glob"],
	"trophig" : lon_min["glob"],
	"troptop" : lon_min["glob"],
	"soutlow" : lon_min["glob"],
	"soutmid" : lon_min["glob"],
	"southig" : lon_min["glob"],
	"souttop" : lon_min["glob"],
	"spollow" : lon_min["glob"],
	"spolmid" : lon_min["glob"],
	"spolhig" : lon_min["glob"],
	"spoltop" : lon_min["glob"],
	"indialow" : lon_min["indi"],
	"indiamid" : lon_min["indi"],
	"indiahig" : lon_min["indi"],
	"indiatop" : lon_min["indi"],
	}

dom_lonmax={
	"globlow" : lon_max["glob"],
	"globmid" : lon_max["glob"],
	"globhig" : lon_max["glob"],
	"globtop" : lon_max["glob"],
	"npollow" : lon_max["glob"],
	"npolmid" : lon_max["glob"],
	"npolhig" : lon_max["glob"],
	"npoltop" : lon_max["glob"],
	"nortlow" : lon_max["glob"],
	"nortmid" : lon_max["glob"],
	"northig" : lon_max["glob"],
	"norttop" : lon_max["glob"],
	"troplow" : lon_max["glob"],
	"tropmid" : lon_max["glob"],
	"trophig" : lon_max["glob"],
	"troptop" : lon_max["glob"],
	"soutlow" : lon_max["glob"],
	"soutmid" : lon_max["glob"],
	"southig" : lon_max["glob"],
	"souttop" : lon_max["glob"],
	"spollow" : lon_max["glob"],
	"spolmid" : lon_max["glob"],
	"spolhig" : lon_max["glob"],
	"spoltop" : lon_max["glob"],
	"indialow" : lon_max["indi"],
	"indiamid" : lon_max["indi"],
	"indiahig" : lon_max["indi"],
	"indiatop" : lon_max["indi"],
	}

dom_latmin={
	"globlow" : lat_min["glob"],
	"globmid" : lat_min["glob"],
	"globhig" : lat_min["glob"],
	"globtop" : lat_min["glob"],
	"npollow" : lat_min["npol"],
	"npolmid" : lat_min["npol"],
	"npolhig" : lat_min["npol"],
	"npoltop" : lat_min["npol"],
	"nortlow" : lat_min["nort"],
	"nortmid" : lat_min["nort"],
	"northig" : lat_min["nort"],
	"norttop" : lat_min["nort"],
	"troplow" : lat_min["trop"],
	"tropmid" : lat_min["trop"],
	"trophig" : lat_min["trop"],
	"troptop" : lat_min["trop"],
	"soutlow" : lat_min["sout"],
	"soutmid" : lat_min["sout"],
	"southig" : lat_min["sout"],
	"souttop" : lat_min["sout"],
	"spollow" : lat_min["spol"],
	"spolmid" : lat_min["spol"],
	"spolhig" : lat_min["spol"],
	"spoltop" : lat_min["spol"],
	"indialow" : lat_min["indi"],
	"indiamid" : lat_min["indi"],
	"indiahig" : lat_min["indi"],
	"indiatop" : lat_min["indi"],
	}

dom_latmax={
	"globlow" : lat_max["glob"],
	"globmid" : lat_max["glob"],
	"globhig" : lat_max["glob"],
	"globtop" : lat_max["glob"],
	"npollow" : lat_max["npol"],
	"npolmid" : lat_max["npol"],
	"npolhig" : lat_max["npol"],
	"npoltop" : lat_max["npol"],
	"nortlow" : lat_max["nort"],
	"nortmid" : lat_max["nort"],
	"northig" : lat_max["nort"],
	"norttop" : lat_max["nort"],
	"troplow" : lat_max["trop"],
	"tropmid" : lat_max["trop"],
	"trophig" : lat_max["trop"],
	"troptop" : lat_max["trop"],
	"soutlow" : lat_max["sout"],
	"soutmid" : lat_max["sout"],
	"southig" : lat_max["sout"],
	"souttop" : lat_max["sout"],
	"spollow" : lat_max["spol"],
	"spolmid" : lat_max["spol"],
	"spolhig" : lat_max["spol"],
	"spoltop" : lat_max["spol"],
	"indialow" : lat_max["indi"],
	"indiamid" : lat_max["indi"],
	"indiahig" : lat_max["indi"],
	"indiatop" : lat_max["indi"],
	}

dom_hgtmin={
	"globlow" : hgt_min["low"],
	"globmid" : hgt_min["mid"],
	"globhig" : hgt_min["hig"],
	"globtop" : hgt_min["top"],
	"npollow" : hgt_min["low"],
	"npolmid" : hgt_min["mid"],
	"npolhig" : hgt_min["hig"],
	"npoltop" : hgt_min["top"],
	"nortlow" : hgt_min["low"],
	"nortmid" : hgt_min["mid"],
	"northig" : hgt_min["hig"],
	"norttop" : hgt_min["top"],
	"troplow" : hgt_min["low"],
	"tropmid" : hgt_min["mid"],
	"trophig" : hgt_min["hig"],
	"troptop" : hgt_min["top"],
	"soutlow" : hgt_min["low"],
	"soutmid" : hgt_min["mid"],
	"southig" : hgt_min["hig"],
	"souttop" : hgt_min["top"],
	"spollow" : hgt_min["low"],
	"spolmid" : hgt_min["mid"],
	"spolhig" : hgt_min["hig"],
	"spoltop" : hgt_min["top"],
	"indialow" : hgt_min["low"],
	"indiamid" : hgt_min["mid"],
	"indiahig" : hgt_min["hig"],
	"indiatop" : hgt_min["top"],
	}

dom_hgtmax={
	"globlow" : hgt_max["low"],
	"globmid" : hgt_max["mid"],
	"globhig" : hgt_max["hig"],
	"globtop" : hgt_max["top"],
	"npollow" : hgt_max["low"],
	"npolmid" : hgt_max["mid"],
	"npolhig" : hgt_max["hig"],
	"npoltop" : hgt_max["top"],
	"nortlow" : hgt_max["low"],
	"nortmid" : hgt_max["mid"],
	"northig" : hgt_max["hig"],
	"norttop" : hgt_max["top"],
	"troplow" : hgt_max["low"],
	"tropmid" : hgt_max["mid"],
	"trophig" : hgt_max["hig"],
	"troptop" : hgt_max["top"],
	"soutlow" : hgt_max["low"],
	"soutmid" : hgt_max["mid"],
	"southig" : hgt_max["hig"],
	"souttop" : hgt_max["top"],
	"spollow" : hgt_max["low"],
	"spolmid" : hgt_max["mid"],
	"spolhig" : hgt_max["hig"],
	"spoltop" : hgt_max["top"],
	"indialow" : hgt_max["low"],
	"indiamid" : hgt_max["mid"],
	"indiahig" : hgt_max["hig"],
	"indiatop" : hgt_max["top"],
	}
